version: '2'
services:
    cucumber-app:
        image: cucumber
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cucumber-mysql:3306/cucumber?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cucumber-mysql:
        extends:
            file: mysql.yml
            service: cucumber-mysql
